import { JikanAnime, GenreData } from "./types";

export const FALLBACK_ANIME_LIST: JikanAnime[] = [
  {
    mal_id: 52991,
    url: "https://myanimelist.net/anime/52991/Sousou_no_Frieren",
    images: {
      jpg: {
        image_url: "https://cdn.myanimelist.net/images/anime/1015/138006.jpg",
        small_image_url: "https://cdn.myanimelist.net/images/anime/1015/138006t.jpg",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1015/138006l.jpg",
      },
      webp: {
        image_url: "https://cdn.myanimelist.net/images/anime/1015/138006.webp",
        small_image_url: "https://cdn.myanimelist.net/images/anime/1015/138006t.webp",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1015/138006l.webp",
      },
    },
    trailer: {
      youtube_id: "qgQunxD0qMo",
      url: "https://www.youtube.com/watch?v=qgQunxD0qMo",
      embed_url: "https://www.youtube.com/embed/qgQunxD0qMo?enablejsapi=1&wmode=opaque&autoplay=1",
    },
    approved: true,
    titles: [{ type: "Default", title: "Sousou no Frieren" }],
    title: "Sousou no Frieren",
    title_english: "Frieren: Beyond Journey's End",
    title_japanese: "葬送のフリーレン",
    type: "TV",
    source: "Manga",
    episodes: 28,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2023-09-29T00:00:00+00:00",
      to: "2024-03-22T00:00:00+00:00",
      prop: { from: { day: 29, month: 9, year: 2023 }, to: { day: 22, month: 3, year: 2024 } },
      string: "Sep 29, 2023 to Mar 22, 2024",
    },
    duration: "24 min per ep",
    rating: "PG-13 - Teens 13 or older",
    score: 9.38,
    scored_by: 450000,
    rank: 1,
    popularity: 45,
    members: 890000,
    favorites: 42000,
    synopsis:
      "Raja Iblis telah dikalahkan, dan kelompok pahlawan yang menang bubar setelah kembali ke rumah. Mereka berempat—penyihir Frieren, pahlawan Himmel, pendeta Heiter, dan prajurit Eisen—mengenang perjalanan selama satu dekade mereka saat tiba saatnya untuk mengucapkan selamat tinggal. Namun berlalunya waktu berbeda bagi para elf, sehingga Frieren menyaksikan teman-temannya perlahan-lahan meninggal dunia satu per satu.",
    background: "Anime of the Year 2024.",
    season: "fall",
    year: 2023,
    genres: [
      { mal_id: 2, name: "Adventure" },
      { mal_id: 8, name: "Drama" },
      { mal_id: 10, name: "Fantasy" },
    ],
    themes: [],
    demographics: [{ mal_id: 27, name: "Shounen" }],
    studios: [{ mal_id: 11, name: "Madhouse" }],
    producers: [{ mal_id: 16, name: "TOHO animation" }],
  },
  {
    mal_id: 52299,
    url: "https://myanimelist.net/anime/52299/Ore_dake_Level_Up_na_Ken",
    images: {
      jpg: {
        image_url: "https://cdn.myanimelist.net/images/anime/1484/141380.jpg",
        small_image_url: "https://cdn.myanimelist.net/images/anime/1484/141380t.jpg",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1484/141380l.jpg",
      },
      webp: {
        image_url: "https://cdn.myanimelist.net/images/anime/1484/141380.webp",
        small_image_url: "https://cdn.myanimelist.net/images/anime/1484/141380t.webp",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1484/141380l.webp",
      },
    },
    trailer: {
      youtube_id: "v94d_dY_Zt0",
      url: "https://www.youtube.com/watch?v=v94d_dY_Zt0",
      embed_url: "https://www.youtube.com/embed/v94d_dY_Zt0?enablejsapi=1&wmode=opaque&autoplay=1",
    },
    approved: true,
    titles: [{ type: "Default", title: "Solo Leveling" }],
    title: "Solo Leveling",
    title_english: "Solo Leveling Season 2: Arise from the Shadow",
    title_japanese: "俺だけレベルアップな件",
    type: "TV",
    source: "Web manhwa",
    episodes: 12,
    status: "Currently Airing",
    airing: true,
    aired: {
      from: "2024-01-07T00:00:00+00:00",
      to: null,
      prop: { from: { day: 7, month: 1, year: 2024 }, to: { day: null, month: null, year: null } },
      string: "Jan 7, 2024 to ?",
    },
    duration: "23 min per ep",
    rating: "R - 17+ (violence & profanity)",
    score: 8.84,
    scored_by: 380000,
    rank: 85,
    popularity: 20,
    members: 650000,
    favorites: 28000,
    synopsis:
      "Sepuluh tahun yang lalu, 'Gerbang' muncul dan menghubungkan dunia nyata dengan alam sihir dan monster. Untuk memerangi binatang buas yang keji ini, orang-orang biasa menerima kekuatan manusia super dan dikenal sebagai 'Hunter'. Sung Jin-Woo yang berusia dua puluh tahun adalah salah satu Pemburu tersebut, tetapi ia dikenal sebagai 'Yang Terlemah di Dunia'.",
    background: "Based on the bestselling Korean webtoon.",
    season: "winter",
    year: 2024,
    genres: [
      { mal_id: 1, name: "Action" },
      { mal_id: 2, name: "Adventure" },
      { mal_id: 10, name: "Fantasy" },
    ],
    themes: [],
    demographics: [],
    studios: [{ mal_id: 56, name: "A-1 Pictures" }],
    producers: [{ mal_id: 17, name: "Aniplex" }],
  },
  {
    mal_id: 51009,
    url: "https://myanimelist.net/anime/51009/Jujutsu_Kaisen_2nd_Season",
    images: {
      jpg: {
        image_url: "https://cdn.myanimelist.net/images/anime/1171/109222.jpg",
        small_image_url: "https://cdn.myanimelist.net/images/anime/1171/109222t.jpg",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1171/109222l.jpg",
      },
      webp: {
        image_url: "https://cdn.myanimelist.net/images/anime/1171/109222.webp",
        small_image_url: "https://cdn.myanimelist.net/images/anime/1171/109222t.webp",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1171/109222l.webp",
      },
    },
    trailer: {
      youtube_id: "O6qVieflwQs",
      url: "https://www.youtube.com/watch?v=O6qVieflwQs",
      embed_url: "https://www.youtube.com/embed/O6qVieflwQs?enablejsapi=1&wmode=opaque&autoplay=1",
    },
    approved: true,
    titles: [{ type: "Default", title: "Jujutsu Kaisen Season 2" }],
    title: "Jujutsu Kaisen Season 2",
    title_english: "Jujutsu Kaisen: Shibuya Incident",
    title_japanese: "呪術廻戦 懐玉・玉折／渋谷事変",
    type: "TV",
    source: "Manga",
    episodes: 23,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2023-07-06T00:00:00+00:00",
      to: "2023-12-28T00:00:00+00:00",
      prop: { from: { day: 6, month: 7, year: 2023 }, to: { day: 28, month: 12, year: 2023 } },
      string: "Jul 6, 2023 to Dec 28, 2023",
    },
    duration: "23 min per ep",
    rating: "R - 17+ (violence & profanity)",
    score: 8.92,
    scored_by: 520000,
    rank: 18,
    popularity: 12,
    members: 950000,
    favorites: 35000,
    synopsis:
      "Tahun 2006, musim semi. Satoru Gojo dan Suguru Geto, dua penyihir jujutsu yang tak tertandingi dari SMA Jujutsu Tokyo, ditugaskan untuk mengawal dan melenyapkan 'Wadah Plasma Bintang', seorang gadis muda bernama Riko Amanai.",
    background: "Shibuya Incident Arc.",
    season: "summer",
    year: 2023,
    genres: [
      { mal_id: 1, name: "Action" },
      { mal_id: 10, name: "Fantasy" },
    ],
    themes: [],
    demographics: [{ mal_id: 27, name: "Shounen" }],
    studios: [{ mal_id: 569, name: "MAPPA" }],
    producers: [{ mal_id: 16, name: "TOHO animation" }],
  },
  {
    mal_id: 21,
    url: "https://myanimelist.net/anime/21/One_Piece",
    images: {
      jpg: {
        image_url: "https://cdn.myanimelist.net/images/anime/6/73245.jpg",
        small_image_url: "https://cdn.myanimelist.net/images/anime/6/73245t.jpg",
        large_image_url: "https://cdn.myanimelist.net/images/anime/6/73245l.jpg",
      },
      webp: {
        image_url: "https://cdn.myanimelist.net/images/anime/6/73245.webp",
        small_image_url: "https://cdn.myanimelist.net/images/anime/6/73245t.webp",
        large_image_url: "https://cdn.myanimelist.net/images/anime/6/73245l.webp",
      },
    },
    trailer: {
      youtube_id: "l_98K4_6UQ0",
      url: "https://www.youtube.com/watch?v=l_98K4_6UQ0",
      embed_url: "https://www.youtube.com/embed/l_98K4_6UQ0?enablejsapi=1&wmode=opaque&autoplay=1",
    },
    approved: true,
    titles: [{ type: "Default", title: "One Piece" }],
    title: "One Piece",
    title_english: "One Piece (Egghead Arc)",
    title_japanese: "ONE PIECE",
    type: "TV",
    source: "Manga",
    episodes: 1120,
    status: "Currently Airing",
    airing: true,
    aired: {
      from: "1999-10-20T00:00:00+00:00",
      to: null,
      prop: { from: { day: 20, month: 10, year: 1999 }, to: { day: null, month: null, year: null } },
      string: "Oct 20, 1999 to ?",
    },
    duration: "24 min per ep",
    rating: "PG-13 - Teens 13 or older",
    score: 8.72,
    scored_by: 1200000,
    rank: 48,
    popularity: 2,
    members: 2200000,
    favorites: 180000,
    synopsis:
      "Gol D. Roger dikenal sebagai 'Raja Bajak Laut', makhluk terkuat dan paling terkenal yang pernah mengarungi Grand Line. Penangkapan dan eksekusi Roger oleh Pemerintah Dunia membawa perubahan di seluruh dunia. Kata-kata terakhirnya sebelum kematiannya mengungkapkan keberadaan harta karun terbesar di dunia, One Piece.",
    background: "Longest running popular shounen anime.",
    season: "fall",
    year: 1999,
    genres: [
      { mal_id: 1, name: "Action" },
      { mal_id: 2, name: "Adventure" },
      { mal_id: 10, name: "Fantasy" },
    ],
    themes: [],
    demographics: [{ mal_id: 27, name: "Shounen" }],
    studios: [{ mal_id: 18, name: "Toei Animation" }],
    producers: [{ mal_id: 23, name: "Fuji TV" }],
  },
  {
    mal_id: 54857,
    url: "https://myanimelist.net/anime/54857/Kimetsu_no_Yaiba_Hashira_Geiko-hen",
    images: {
      jpg: {
        image_url: "https://cdn.myanimelist.net/images/anime/1702/136843.jpg",
        small_image_url: "https://cdn.myanimelist.net/images/anime/1702/136843t.jpg",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1702/136843l.jpg",
      },
      webp: {
        image_url: "https://cdn.myanimelist.net/images/anime/1702/136843.webp",
        small_image_url: "https://cdn.myanimelist.net/images/anime/1702/136843t.webp",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1702/136843l.webp",
      },
    },
    trailer: {
      youtube_id: "x7u4T4Jc3Jk",
      url: "https://www.youtube.com/watch?v=x7u4T4Jc3Jk",
      embed_url: "https://www.youtube.com/embed/x7u4T4Jc3Jk?enablejsapi=1&wmode=opaque&autoplay=1",
    },
    approved: true,
    titles: [{ type: "Default", title: "Kimetsu no Yaiba: Hashira Geiko-hen" }],
    title: "Kimetsu no Yaiba: Hashira Geiko-hen",
    title_english: "Demon Slayer: Hashira Training Arc",
    title_japanese: "鬼滅の刃 柱稽古編",
    type: "TV",
    source: "Manga",
    episodes: 8,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2024-05-12T00:00:00+00:00",
      to: "2024-06-30T00:00:00+00:00",
      prop: { from: { day: 12, month: 5, year: 2024 }, to: { day: 30, month: 6, year: 2024 } },
      string: "May 12, 2024 to Jun 30, 2024",
    },
    duration: "24 min per ep",
    rating: "R - 17+ (violence & profanity)",
    score: 8.88,
    scored_by: 290000,
    rank: 30,
    popularity: 28,
    members: 620000,
    favorites: 19000,
    synopsis:
      "Tanjiro pergi menemui Hashira Batu, Himejima, yang berniat mempersiapkannya menghadapi pertempuran yang akan datang. Pelatihan untuk menjadi Hashira—anggota berperingkat tinggi dari Korps Pembunuh Iblis—sangat ketat dan menuntut.",
    background: "Hashira Training Arc by ufotable.",
    season: "spring",
    year: 2024,
    genres: [
      { mal_id: 1, name: "Action" },
      { mal_id: 10, name: "Fantasy" },
    ],
    themes: [],
    demographics: [{ mal_id: 27, name: "Shounen" }],
    studios: [{ mal_id: 43, name: "ufotable" }],
    producers: [{ mal_id: 17, name: "Aniplex" }],
  },
  {
    mal_id: 48583,
    url: "https://myanimelist.net/anime/48583/Shingeki_no_Kyojin__The_Final_Season_Part_2",
    images: {
      jpg: {
        image_url: "https://cdn.myanimelist.net/images/anime/1000/110531.jpg",
        small_image_url: "https://cdn.myanimelist.net/images/anime/1000/110531t.jpg",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1000/110531l.jpg",
      },
      webp: {
        image_url: "https://cdn.myanimelist.net/images/anime/1000/110531.webp",
        small_image_url: "https://cdn.myanimelist.net/images/anime/1000/110531t.webp",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1000/110531l.webp",
      },
    },
    trailer: {
      youtube_id: "EIVVnLlhz1E",
      url: "https://www.youtube.com/watch?v=EIVVnLlhz1E",
      embed_url: "https://www.youtube.com/embed/EIVVnLlhz1E?enablejsapi=1&wmode=opaque&autoplay=1",
    },
    approved: true,
    titles: [{ type: "Default", title: "Shingeki no Kyojin: The Final Season" }],
    title: "Shingeki no Kyojin: The Final Season",
    title_english: "Attack on Titan: The Final Season",
    title_japanese: "進撃の巨人 The Final Season",
    type: "TV",
    source: "Manga",
    episodes: 28,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2020-12-07T00:00:00+00:00",
      to: "2023-11-05T00:00:00+00:00",
      prop: { from: { day: 7, month: 12, year: 2020 }, to: { day: 5, month: 11, year: 2023 } },
      string: "Dec 7, 2020 to Nov 5, 2023",
    },
    duration: "23 min per ep",
    rating: "R - 17+ (violence & profanity)",
    score: 9.05,
    scored_by: 850000,
    rank: 6,
    popularity: 4,
    members: 1400000,
    favorites: 68000,
    synopsis:
      "Berbalik melawan mantan sekutu dan musuhnya, Eren Yeager melancarkan rencana yang membawa bencana. Di bawah bimbingan Titan Binatang Zeke Yeager, Eren mengambil tindakan ekstrem untuk mengakhiri perseteruan kuno antara Marley dan Eldia.",
    background: "Attack on Titan Final Season culmination.",
    season: "winter",
    year: 2021,
    genres: [
      { mal_id: 1, name: "Action" },
      { mal_id: 8, name: "Drama" },
      { mal_id: 41, name: "Suspense" },
    ],
    themes: [],
    demographics: [{ mal_id: 27, name: "Shounen" }],
    studios: [{ mal_id: 569, name: "MAPPA" }],
    producers: [{ mal_id: 10, name: "Production I.G" }],
  },
  {
    mal_id: 54112,
    url: "https://myanimelist.net/anime/54112/Bleach__Sennen_Kessen-hen_-_Soukoku-tan",
    images: {
      jpg: {
        image_url: "https://cdn.myanimelist.net/images/anime/1764/126627.jpg",
        small_image_url: "https://cdn.myanimelist.net/images/anime/1764/126627t.jpg",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1764/126627l.jpg",
      },
      webp: {
        image_url: "https://cdn.myanimelist.net/images/anime/1764/126627.webp",
        small_image_url: "https://cdn.myanimelist.net/images/anime/1764/126627t.webp",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1764/126627l.webp",
      },
    },
    trailer: {
      youtube_id: "78WIYzX_Edg",
      url: "https://www.youtube.com/watch?v=78WIYzX_Edg",
      embed_url: "https://www.youtube.com/embed/78WIYzX_Edg?enablejsapi=1&wmode=opaque&autoplay=1",
    },
    approved: true,
    titles: [{ type: "Default", title: "Bleach: Sennen Kessen-hen" }],
    title: "Bleach: Sennen Kessen-hen",
    title_english: "Bleach: Thousand-Year Blood War",
    title_japanese: "BLEACH 千年血戦篇",
    type: "TV",
    source: "Manga",
    episodes: 26,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2022-10-11T00:00:00+00:00",
      to: "2023-09-30T00:00:00+00:00",
      prop: { from: { day: 11, month: 10, year: 2022 }, to: { day: 30, month: 9, year: 2023 } },
      string: "Oct 11, 2022 to Sep 30, 2023",
    },
    duration: "24 min per ep",
    rating: "R - 17+ (violence & profanity)",
    score: 8.89,
    scored_by: 310000,
    rank: 22,
    popularity: 35,
    members: 580000,
    favorites: 22000,
    synopsis:
      "Perang suci antara Shinigami dan Quincy pecah. Yhwach, bapak segala Quincy, mendeklarasikan perang terhadap Soul Society dan memimpin pasukan Wandenreich untuk menghancurkan segalanya.",
    background: "Bleach TYBW Part 1 & 2.",
    season: "fall",
    year: 2022,
    genres: [
      { mal_id: 1, name: "Action" },
      { mal_id: 2, name: "Adventure" },
      { mal_id: 10, name: "Fantasy" },
    ],
    themes: [],
    demographics: [{ mal_id: 27, name: "Shounen" }],
    studios: [{ mal_id: 1, name: "Studio Pierrot" }],
    producers: [{ mal_id: 16, name: "TV Tokyo" }],
  },
  {
    mal_id: 52034,
    url: "https://myanimelist.net/anime/52034/Oshi_no_Ko",
    images: {
      jpg: {
        image_url: "https://cdn.myanimelist.net/images/anime/1806/134019.jpg",
        small_image_url: "https://cdn.myanimelist.net/images/anime/1806/134019t.jpg",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1806/134019l.jpg",
      },
      webp: {
        image_url: "https://cdn.myanimelist.net/images/anime/1806/134019.webp",
        small_image_url: "https://cdn.myanimelist.net/images/anime/1806/134019t.webp",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1806/134019l.webp",
      },
    },
    trailer: {
      youtube_id: "g3bL9H_r4cE",
      url: "https://www.youtube.com/watch?v=g3bL9H_r4cE",
      embed_url: "https://www.youtube.com/embed/g3bL9H_r4cE?enablejsapi=1&wmode=opaque&autoplay=1",
    },
    approved: true,
    titles: [{ type: "Default", title: "Oshi no Ko" }],
    title: "Oshi no Ko",
    title_english: "Oshi no Ko Season 2",
    title_japanese: "【推しの子】",
    type: "TV",
    source: "Manga",
    episodes: 24,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2023-04-12T00:00:00+00:00",
      to: "2024-09-25T00:00:00+00:00",
      prop: { from: { day: 12, month: 4, year: 2023 }, to: { day: 25, month: 9, year: 2024 } },
      string: "Apr 12, 2023 to Sep 25, 2024",
    },
    duration: "24 min per ep",
    rating: "PG-13 - Teens 13 or older",
    score: 8.91,
    scored_by: 420000,
    rank: 19,
    popularity: 15,
    members: 780000,
    favorites: 31000,
    synopsis:
      "Goro Amemiya, seorang dokter kandungan pedesaan dan penggemar berat idola Ai Hoshino, terkejut saat Ai datang ke kliniknya dalam keadaan hamil kembar. Goro berjanji akan membantu persalinan Ai dengan selamat, namun nasib buruk menimpanya sebelum kelahiran tersebut.",
    background: "Hit anime exploring the dark side of the entertainment industry.",
    season: "spring",
    year: 2023,
    genres: [
      { mal_id: 8, name: "Drama" },
      { mal_id: 41, name: "Suspense" },
    ],
    themes: [],
    demographics: [{ mal_id: 42, name: "Seinen" }],
    studios: [{ mal_id: 95, name: "Doga Kobo" }],
    producers: [{ mal_id: 17, name: "Kadokawa" }],
  },
];

export const FALLBACK_GENRES: GenreData[] = [
  { mal_id: 1, name: "Action", count: 4500 },
  { mal_id: 2, name: "Adventure", count: 3200 },
  { mal_id: 4, name: "Comedy", count: 6800 },
  { mal_id: 8, name: "Drama", count: 2900 },
  { mal_id: 10, name: "Fantasy", count: 5100 },
  { mal_id: 22, name: "Romance", count: 2400 },
  { mal_id: 24, name: "Sci-Fi", count: 3100 },
  { mal_id: 36, name: "Slice of Life", count: 1900 },
  { mal_id: 37, name: "Supernatural", count: 2100 },
  { mal_id: 41, name: "Suspense", count: 850 },
];
