import { JikanAnime, GenreData } from "./types";

export const FALLBACK_ANIME_LIST: JikanAnime[] = [
  {
    mal_id: 52991,
    url: "https://myanimelist.net/anime/52991/Sousou_no_Frieren",
    images: {
      jpg: {
        image_url: "https://cdn.myanimelist.net/images/anime/1015/138006.jpg",
        small_image_url: "https://cdn.myanimelist.net/images/anime/1015/138006t.jpg",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1015/138006l.jpg",
      },
      webp: {
        image_url: "https://cdn.myanimelist.net/images/anime/1015/138006.webp",
        small_image_url: "https://cdn.myanimelist.net/images/anime/1015/138006t.webp",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1015/138006l.webp",
      },
    },
    trailer: {
      youtube_id: "qgQunxD0qMo",
      url: "https://www.youtube.com/watch?v=qgQunxD0qMo",
      embed_url: "https://www.youtube.com/embed/qgQunxD0qMo?enablejsapi=1&wmode=opaque&autoplay=1",
    },
    approved: true,
    titles: [{ type: "Default", title: "Sousou no Frieren" }],
    title: "Sousou no Frieren",
    title_english: "Frieren: Beyond Journey's End",
    title_japanese: "葬送のフリーレン",
    type: "TV",
    source: "Manga",
    episodes: 28,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2023-09-29T00:00:00+00:00",
      to: "2024-03-22T00:00:00+00:00",
      prop: { from: { day: 29, month: 9, year: 2023 }, to: { day: 22, month: 3, year: 2024 } },
      string: "Sep 29, 2023 to Mar 22, 2024",
    },
    duration: "24 min per ep",
    rating: "PG-13 - Teens 13 or older",
    score: 9.39,
    scored_by: 460000,
    rank: 1,
    popularity: 45,
    members: 820000,
    favorites: 42000,
    synopsis:
      "Raja Iblis telah dikalahkan, dan kelompok pahlawan yang menang kembali ke rumah sebelum bubar. Keempatnya—penyihir Frieren, pahlawan Himmel, pendeta Heiter, dan prajurit Eisen—mengenang perjalanan panjang mereka selama satu dekade. Sebagai elf yang berumur ribuan tahun, Frieren menyaksikan sahabat-sahabat manusianya menua dan meninggal, memicu perjalanan barunya untuk memahami arti hidup manusia.",
    background: "Pemenang Anime of the Year dengan animasi spektakuler dari Madhouse.",
    season: "fall",
    year: 2023,
    genres: [
      { mal_id: 2, name: "Adventure" },
      { mal_id: 8, name: "Drama" },
      { mal_id: 10, name: "Fantasy" },
    ],
    themes: [],
    demographics: [{ mal_id: 27, name: "Shounen" }],
    studios: [{ mal_id: 11, name: "Madhouse" }],
    producers: [{ mal_id: 17, name: "Aniplex" }],
  },
  {
    mal_id: 52299,
    url: "https://myanimelist.net/anime/52299/Ore_dake_Level_Up_na_Ken",
    images: {
      jpg: {
        image_url: "https://cdn.myanimelist.net/images/anime/1484/141380.jpg",
        small_image_url: "https://cdn.myanimelist.net/images/anime/1484/141380t.jpg",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1484/141380l.jpg",
      },
      webp: {
        image_url: "https://cdn.myanimelist.net/images/anime/1484/141380.webp",
        small_image_url: "https://cdn.myanimelist.net/images/anime/1484/141380t.webp",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1484/141380l.webp",
      },
    },
    trailer: {
      youtube_id: "s4OWk4_yEoc",
      url: "https://www.youtube.com/watch?v=s4OWk4_yEoc",
      embed_url: "https://www.youtube.com/embed/s4OWk4_yEoc?enablejsapi=1&wmode=opaque&autoplay=1",
    },
    approved: true,
    titles: [{ type: "Default", title: "Ore dake Level Up na Ken" }],
    title: "Solo Leveling",
    title_english: "Solo Leveling Season 2: Arise from the Shadow",
    title_japanese: "俺だけレベルアップな件",
    type: "TV",
    source: "Web manga",
    episodes: 12,
    status: "Currently Airing",
    airing: true,
    aired: {
      from: "2024-01-07T00:00:00+00:00",
      to: null,
      prop: { from: { day: 7, month: 1, year: 2024 }, to: { day: null, month: null, year: null } },
      string: "Jan 7, 2024 to present",
    },
    duration: "23 min per ep",
    rating: "R - 17+ (violence & profanity)",
    score: 8.52,
    scored_by: 380000,
    rank: 110,
    popularity: 32,
    members: 710000,
    favorites: 28000,
    synopsis:
      "Satu dekade lalu, 'Gerbang' yang menghubungkan dunia manusia ke dunia monster muncul. Sung Jinwoo, pemburu peringkat-E yang dijuluki 'Senjata Terlemah Umat Manusia', terbangun di rumah sakit setelah misi mematikan di Dungeon Ganda dengan sistem pencarian unik di depan matanya.",
    background: "Adaptasi manhwa Korea legendaris oleh studio A-1 Pictures.",
    season: "winter",
    year: 2024,
    genres: [
      { mal_id: 1, name: "Action" },
      { mal_id: 2, name: "Adventure" },
      { mal_id: 10, name: "Fantasy" },
    ],
    themes: [],
    demographics: [],
    studios: [{ mal_id: 56, name: "A-1 Pictures" }],
    producers: [{ mal_id: 17, name: "Aniplex" }],
  },
  {
    mal_id: 51009,
    url: "https://myanimelist.net/anime/51009/Jujutsu_Kaisen_2nd_Season",
    images: {
      jpg: {
        image_url: "https://cdn.myanimelist.net/images/anime/1171/109222.jpg",
        small_image_url: "https://cdn.myanimelist.net/images/anime/1171/109222t.jpg",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1171/109222l.jpg",
      },
      webp: {
        image_url: "https://cdn.myanimelist.net/images/anime/1171/109222.webp",
        small_image_url: "https://cdn.myanimelist.net/images/anime/1171/109222t.webp",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1171/109222l.webp",
      },
    },
    trailer: {
      youtube_id: "O6qVieflwQs",
      url: "https://www.youtube.com/watch?v=O6qVieflwQs",
      embed_url: "https://www.youtube.com/embed/O6qVieflwQs?enablejsapi=1&wmode=opaque&autoplay=1",
    },
    approved: true,
    titles: [{ type: "Default", title: "Jujutsu Kaisen Season 2" }],
    title: "Jujutsu Kaisen Season 2",
    title_english: "Jujutsu Kaisen: Shibuya Incident Arc",
    title_japanese: "呪術廻戦 懐玉・玉折／渋谷事変",
    type: "TV",
    source: "Manga",
    episodes: 23,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2023-07-06T00:00:00+00:00",
      to: "2023-12-28T00:00:00+00:00",
      prop: { from: { day: 6, month: 7, year: 2023 }, to: { day: 28, month: 12, year: 2023 } },
      string: "Jul 6, 2023 to Dec 28, 2023",
    },
    duration: "23 min per ep",
    rating: "R - 17+ (violence & profanity)",
    score: 8.92,
    scored_by: 520000,
    rank: 18,
    popularity: 12,
    members: 950000,
    favorites: 35000,
    synopsis:
      "Tahun 2006, musim semi. Satoru Gojo dan Suguru Geto, dua penyihir jujutsu yang tak tertandingi dari SMA Jujutsu Tokyo, ditugaskan untuk mengawal dan melenyapkan 'Wadah Plasma Bintang', seorang gadis muda bernama Riko Amanai.",
    background: "Shibuya Incident Arc.",
    season: "summer",
    year: 2023,
    genres: [
      { mal_id: 1, name: "Action" },
      { mal_id: 10, name: "Fantasy" },
    ],
    themes: [],
    demographics: [{ mal_id: 27, name: "Shounen" }],
    studios: [{ mal_id: 569, name: "MAPPA" }],
    producers: [{ mal_id: 16, name: "TOHO animation" }],
  },
  {
    mal_id: 21,
    url: "https://myanimelist.net/anime/21/One_Piece",
    images: {
      jpg: {
        image_url: "https://cdn.myanimelist.net/images/anime/6/73245.jpg",
        small_image_url: "https://cdn.myanimelist.net/images/anime/6/73245t.jpg",
        large_image_url: "https://cdn.myanimelist.net/images/anime/6/73245l.jpg",
      },
      webp: {
        image_url: "https://cdn.myanimelist.net/images/anime/6/73245.webp",
        small_image_url: "https://cdn.myanimelist.net/images/anime/6/73245t.webp",
        large_image_url: "https://cdn.myanimelist.net/images/anime/6/73245l.webp",
      },
    },
    trailer: {
      youtube_id: "l_98K4_6UQ0",
      url: "https://www.youtube.com/watch?v=l_98K4_6UQ0",
      embed_url: "https://www.youtube.com/embed/l_98K4_6UQ0?enablejsapi=1&wmode=opaque&autoplay=1",
    },
    approved: true,
    titles: [{ type: "Default", title: "One Piece" }],
    title: "One Piece",
    title_english: "One Piece (Egghead Arc)",
    title_japanese: "ONE PIECE",
    type: "TV",
    source: "Manga",
    episodes: 1120,
    status: "Currently Airing",
    airing: true,
    aired: {
      from: "1999-10-20T00:00:00+00:00",
      to: null,
      prop: { from: { day: 20, month: 10, year: 1999 }, to: { day: null, month: null, year: null } },
      string: "Oct 20, 1999 to present",
    },
    duration: "24 min per ep",
    rating: "PG-13 - Teens 13 or older",
    score: 8.72,
    scored_by: 1200000,
    rank: 48,
    popularity: 2,
    members: 2200000,
    favorites: 180000,
    synopsis:
      "Gol D. Roger dikenal sebagai 'Raja Bajak Laut', makhluk terkuat dan paling terkenal yang pernah mengarungi Grand Line. Penangkapan dan eksekusi Roger oleh Pemerintah Dunia membawa perubahan di seluruh dunia. Kata-kata terakhirnya sebelum kematiannya mengungkapkan keberadaan harta karun terbesar di dunia, One Piece.",
    background: "Anime terpopuler dan terpanjang sepanjang masa.",
    season: "fall",
    year: 1999,
    genres: [
      { mal_id: 1, name: "Action" },
      { mal_id: 2, name: "Adventure" },
      { mal_id: 10, name: "Fantasy" },
    ],
    themes: [],
    demographics: [{ mal_id: 27, name: "Shounen" }],
    studios: [{ mal_id: 18, name: "Toei Animation" }],
    producers: [{ mal_id: 23, name: "Fuji TV" }],
  },
  {
    mal_id: 54857,
    url: "https://myanimelist.net/anime/54857/Kimetsu_no_Yaiba_Hashira_Geiko-hen",
    images: {
      jpg: {
        image_url: "https://cdn.myanimelist.net/images/anime/1702/136843.jpg",
        small_image_url: "https://cdn.myanimelist.net/images/anime/1702/136843t.jpg",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1702/136843l.jpg",
      },
      webp: {
        image_url: "https://cdn.myanimelist.net/images/anime/1702/136843.webp",
        small_image_url: "https://cdn.myanimelist.net/images/anime/1702/136843t.webp",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1702/136843l.webp",
      },
    },
    trailer: {
      youtube_id: "x7u4T4Jc3Jk",
      url: "https://www.youtube.com/watch?v=x7u4T4Jc3Jk",
      embed_url: "https://www.youtube.com/embed/x7u4T4Jc3Jk?enablejsapi=1&wmode=opaque&autoplay=1",
    },
    approved: true,
    titles: [{ type: "Default", title: "Kimetsu no Yaiba: Hashira Geiko-hen" }],
    title: "Kimetsu no Yaiba: Hashira Geiko-hen",
    title_english: "Demon Slayer: Hashira Training Arc",
    title_japanese: "鬼滅の刃 柱稽古編",
    type: "TV",
    source: "Manga",
    episodes: 8,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2024-05-12T00:00:00+00:00",
      to: "2024-06-30T00:00:00+00:00",
      prop: { from: { day: 12, month: 5, year: 2024 }, to: { day: 30, month: 6, year: 2024 } },
      string: "May 12, 2024 to Jun 30, 2024",
    },
    duration: "24 min per ep",
    rating: "R - 17+ (violence & profanity)",
    score: 8.88,
    scored_by: 290000,
    rank: 30,
    popularity: 28,
    members: 620000,
    favorites: 19000,
    synopsis:
      "Tanjiro pergi menemui Hashira Batu, Himejima, yang berniat mempersiapkannya menghadapi pertempuran besar melawan Muzan Kibutsuji. Pelatihan bersama para Hashira sangat ketat dan menuntut kekuatan fisik serta mental tertinggi.",
    background: "Hashira Training Arc by ufotable.",
    season: "spring",
    year: 2024,
    genres: [
      { mal_id: 1, name: "Action" },
      { mal_id: 10, name: "Fantasy" },
    ],
    themes: [],
    demographics: [{ mal_id: 27, name: "Shounen" }],
    studios: [{ mal_id: 43, name: "ufotable" }],
    producers: [{ mal_id: 17, name: "Aniplex" }],
  },
  {
    mal_id: 48583,
    url: "https://myanimelist.net/anime/48583/Shingeki_no_Kyojin__The_Final_Season_Part_2",
    images: {
      jpg: {
        image_url: "https://cdn.myanimelist.net/images/anime/1000/110531.jpg",
        small_image_url: "https://cdn.myanimelist.net/images/anime/1000/110531t.jpg",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1000/110531l.jpg",
      },
      webp: {
        image_url: "https://cdn.myanimelist.net/images/anime/1000/110531.webp",
        small_image_url: "https://cdn.myanimelist.net/images/anime/1000/110531t.webp",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1000/110531l.webp",
      },
    },
    trailer: {
      youtube_id: "EIVVnLlhz1E",
      url: "https://www.youtube.com/watch?v=EIVVnLlhz1E",
      embed_url: "https://www.youtube.com/embed/EIVVnLlhz1E?enablejsapi=1&wmode=opaque&autoplay=1",
    },
    approved: true,
    titles: [{ type: "Default", title: "Shingeki no Kyojin: The Final Season" }],
    title: "Shingeki no Kyojin: The Final Season",
    title_english: "Attack on Titan: The Final Season",
    title_japanese: "進撃の巨人 The Final Season",
    type: "TV",
    source: "Manga",
    episodes: 28,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2020-12-07T00:00:00+00:00",
      to: "2023-11-05T00:00:00+00:00",
      prop: { from: { day: 7, month: 12, year: 2020 }, to: { day: 5, month: 11, year: 2023 } },
      string: "Dec 7, 2020 to Nov 5, 2023",
    },
    duration: "23 min per ep",
    rating: "R - 17+ (violence & profanity)",
    score: 9.05,
    scored_by: 850000,
    rank: 6,
    popularity: 4,
    members: 1400000,
    favorites: 68000,
    synopsis:
      "Berbalik melawan mantan sekutu dan musuhnya, Eren Yeager melancarkan rencana Rumbling yang mengguncang bumi. Di bawah kekuatan Titan Perintis, Eren mengambil tindakan ekstrem demi masa depan Pulau Paradis.",
    background: "Klimaks pertarungan epik Attack on Titan oleh MAPPA.",
    season: "winter",
    year: 2021,
    genres: [
      { mal_id: 1, name: "Action" },
      { mal_id: 8, name: "Drama" },
      { mal_id: 41, name: "Suspense" },
    ],
    themes: [],
    demographics: [{ mal_id: 27, name: "Shounen" }],
    studios: [{ mal_id: 569, name: "MAPPA" }],
    producers: [{ mal_id: 10, name: "Production I.G" }],
  },
  {
    mal_id: 57334,
    url: "https://myanimelist.net/anime/57334/Dandadan",
    images: {
      jpg: {
        image_url: "https://cdn.myanimelist.net/images/anime/1136/143527.jpg",
        small_image_url: "https://cdn.myanimelist.net/images/anime/1136/143527t.jpg",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1136/143527l.jpg",
      },
      webp: {
        image_url: "https://cdn.myanimelist.net/images/anime/1136/143527.webp",
        small_image_url: "https://cdn.myanimelist.net/images/anime/1136/143527t.webp",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1136/143527l.webp",
      },
    },
    trailer: {
      youtube_id: "4PauE7n6yqY",
      url: "https://www.youtube.com/watch?v=4PauE7n6yqY",
      embed_url: "https://www.youtube.com/embed/4PauE7n6yqY?enablejsapi=1&wmode=opaque&autoplay=1",
    },
    approved: true,
    titles: [{ type: "Default", title: "Dandadan" }],
    title: "Dandadan",
    title_english: "Dandadan (Sub Indo)",
    title_japanese: "ダンダダン",
    type: "TV",
    source: "Manga",
    episodes: 12,
    status: "Currently Airing",
    airing: true,
    aired: {
      from: "2024-10-04T00:00:00+00:00",
      to: null,
      prop: { from: { day: 4, month: 10, year: 2024 }, to: { day: null, month: null, year: null } },
      string: "Oct 4, 2024 to present",
    },
    duration: "24 min per ep",
    rating: "R - 17+ (violence & profanity)",
    score: 8.78,
    scored_by: 220000,
    rank: 42,
    popularity: 50,
    members: 490000,
    favorites: 18000,
    synopsis:
      "Momo Ayase adalah siswi SMA yang percaya pada hantu tapi meragukan alien, sedangkan teman sekelasnya Okarun meyakini alien tapi menolak keberadaan hantu. Keduanya bertaruh untuk membuktikan keyakinan masing-masing di lokasi berhantu dan terbengkalai.",
    background: "Diproduksi oleh Science SARU dengan visual psychedelic spektakuler.",
    season: "fall",
    year: 2024,
    genres: [
      { mal_id: 1, name: "Action" },
      { mal_id: 4, name: "Comedy" },
      { mal_id: 37, name: "Supernatural" },
    ],
    themes: [],
    demographics: [{ mal_id: 27, name: "Shounen" }],
    studios: [{ mal_id: 1591, name: "Science SARU" }],
    producers: [{ mal_id: 17, name: "Aniplex" }],
  },
  {
    mal_id: 54112,
    url: "https://myanimelist.net/anime/54112/Bleach__Sennen_Kessen-hen_-_Soukoku-tan",
    images: {
      jpg: {
        image_url: "https://cdn.myanimelist.net/images/anime/1764/126627.jpg",
        small_image_url: "https://cdn.myanimelist.net/images/anime/1764/126627t.jpg",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1764/126627l.jpg",
      },
      webp: {
        image_url: "https://cdn.myanimelist.net/images/anime/1764/126627.webp",
        small_image_url: "https://cdn.myanimelist.net/images/anime/1764/126627t.webp",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1764/126627l.webp",
      },
    },
    trailer: {
      youtube_id: "78WIYzX_Edg",
      url: "https://www.youtube.com/watch?v=78WIYzX_Edg",
      embed_url: "https://www.youtube.com/embed/78WIYzX_Edg?enablejsapi=1&wmode=opaque&autoplay=1",
    },
    approved: true,
    titles: [{ type: "Default", title: "Bleach: Sennen Kessen-hen" }],
    title: "Bleach: Sennen Kessen-hen",
    title_english: "Bleach: Thousand-Year Blood War Part 3",
    title_japanese: "BLEACH 千年血戦篇",
    type: "TV",
    source: "Manga",
    episodes: 26,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2022-10-11T00:00:00+00:00",
      to: "2024-12-30T00:00:00+00:00",
      prop: { from: { day: 11, month: 10, year: 2022 }, to: { day: 30, month: 12, year: 2024 } },
      string: "Oct 11, 2022 to Dec 30, 2024",
    },
    duration: "24 min per ep",
    rating: "R - 17+ (violence & profanity)",
    score: 8.89,
    scored_by: 310000,
    rank: 22,
    popularity: 35,
    members: 580000,
    favorites: 22000,
    synopsis:
      "Perang suci antara Shinigami dan Quincy pecah. Yhwach, bapak segala Quincy, mendeklarasikan perang terhadap Soul Society dan memimpin pasukan Wandenreich untuk menghancurkan segalanya.",
    background: "Bleach TYBW Part 1 & 2.",
    season: "fall",
    year: 2022,
    genres: [
      { mal_id: 1, name: "Action" },
      { mal_id: 2, name: "Adventure" },
      { mal_id: 10, name: "Fantasy" },
    ],
    themes: [],
    demographics: [{ mal_id: 27, name: "Shounen" }],
    studios: [{ mal_id: 1, name: "Studio Pierrot" }],
    producers: [{ mal_id: 16, name: "TV Tokyo" }],
  },
  {
    mal_id: 52034,
    url: "https://myanimelist.net/anime/52034/Oshi_no_Ko",
    images: {
      jpg: {
        image_url: "https://cdn.myanimelist.net/images/anime/1806/134019.jpg",
        small_image_url: "https://cdn.myanimelist.net/images/anime/1806/134019t.jpg",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1806/134019l.jpg",
      },
      webp: {
        image_url: "https://cdn.myanimelist.net/images/anime/1806/134019.webp",
        small_image_url: "https://cdn.myanimelist.net/images/anime/1806/134019t.webp",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1806/134019l.webp",
      },
    },
    trailer: {
      youtube_id: "g3bL9H_r4cE",
      url: "https://www.youtube.com/watch?v=g3bL9H_r4cE",
      embed_url: "https://www.youtube.com/embed/g3bL9H_r4cE?enablejsapi=1&wmode=opaque&autoplay=1",
    },
    approved: true,
    titles: [{ type: "Default", title: "Oshi no Ko" }],
    title: "Oshi no Ko",
    title_english: "Oshi no Ko Season 2 (Sub Indo)",
    title_japanese: "【推しの子】",
    type: "TV",
    source: "Manga",
    episodes: 24,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2023-04-12T00:00:00+00:00",
      to: "2024-09-25T00:00:00+00:00",
      prop: { from: { day: 12, month: 4, year: 2023 }, to: { day: 25, month: 9, year: 2024 } },
      string: "Apr 12, 2023 to Sep 25, 2024",
    },
    duration: "24 min per ep",
    rating: "PG-13 - Teens 13 or older",
    score: 8.91,
    scored_by: 420000,
    rank: 19,
    popularity: 15,
    members: 780000,
    favorites: 31000,
    synopsis:
      "Goro Amemiya, dokter kandungan dan penggemar berat idola Ai Hoshino, terkejut saat Ai datang ke kliniknya dalam keadaan hamil kembar. Misteri kelam industri hiburan Jepang terkuak secara dramatis.",
    background: "Anime hit yang mengupas sisi gelap industri hiburan Jepang.",
    season: "spring",
    year: 2023,
    genres: [
      { mal_id: 8, name: "Drama" },
      { mal_id: 41, name: "Suspense" },
    ],
    themes: [],
    demographics: [{ mal_id: 42, name: "Seinen" }],
    studios: [{ mal_id: 95, name: "Doga Kobo" }],
    producers: [{ mal_id: 17, name: "Kadokawa" }],
  },
  {
    mal_id: 54900,
    url: "https://myanimelist.net/anime/54900/Wind_Breaker",
    images: {
      jpg: {
        image_url: "https://cdn.myanimelist.net/images/anime/1818/141444.jpg",
        small_image_url: "https://cdn.myanimelist.net/images/anime/1818/141444t.jpg",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1818/141444l.jpg",
      },
      webp: {
        image_url: "https://cdn.myanimelist.net/images/anime/1818/141444.webp",
        small_image_url: "https://cdn.myanimelist.net/images/anime/1818/141444t.webp",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1818/141444l.webp",
      },
    },
    trailer: {
      youtube_id: "k9hW8wZfG70",
      url: "https://www.youtube.com/watch?v=k9hW8wZfG70",
      embed_url: "https://www.youtube.com/embed/k9hW8wZfG70?enablejsapi=1&wmode=opaque&autoplay=1",
    },
    approved: true,
    titles: [{ type: "Default", title: "Wind Breaker" }],
    title: "Wind Breaker",
    title_english: "Wind Breaker (Sub Indo)",
    title_japanese: "WIND BREAKER",
    type: "TV",
    source: "Manga",
    episodes: 13,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2024-04-05T00:00:00+00:00",
      to: "2024-06-28T00:00:00+00:00",
      prop: { from: { day: 5, month: 4, year: 2024 }, to: { day: 28, month: 6, year: 2024 } },
      string: "Apr 5, 2024 to Jun 28, 2024",
    },
    duration: "23 min per ep",
    rating: "PG-13 - Teens 13 or older",
    score: 8.05,
    scored_by: 180000,
    rank: 510,
    popularity: 130,
    members: 340000,
    favorites: 8500,
    synopsis:
      "Haruka Sakura hanya peduli pada yang terkuat. Mulai masuk SMA Furin yang terkenal dengan murid-murid berandalan, ia mendapati bahwa mereka menggunakan kekuatan tinju mereka untuk melindungi kota dari ancaman luar.",
    background: "Anime aksi berandalan populer karya CloverWorks.",
    season: "spring",
    year: 2024,
    genres: [
      { mal_id: 1, name: "Action" },
      { mal_id: 8, name: "Drama" },
    ],
    themes: [],
    demographics: [{ mal_id: 27, name: "Shounen" }],
    studios: [{ mal_id: 1835, name: "CloverWorks" }],
    producers: [{ mal_id: 17, name: "Aniplex" }],
  },
  {
    mal_id: 54744,
    url: "https://myanimelist.net/anime/54744/Kaijuu_8-gou",
    images: {
      jpg: {
        image_url: "https://cdn.myanimelist.net/images/anime/1970/141870.jpg",
        small_image_url: "https://cdn.myanimelist.net/images/anime/1970/141870t.jpg",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1970/141870l.jpg",
      },
      webp: {
        image_url: "https://cdn.myanimelist.net/images/anime/1970/141870.webp",
        small_image_url: "https://cdn.myanimelist.net/images/anime/1970/141870t.webp",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1970/141870l.webp",
      },
    },
    trailer: {
      youtube_id: "7n_mFVPEApw",
      url: "https://www.youtube.com/watch?v=7n_mFVPEApw",
      embed_url: "https://www.youtube.com/embed/7n_mFVPEApw?enablejsapi=1&wmode=opaque&autoplay=1",
    },
    approved: true,
    titles: [{ type: "Default", title: "Kaijuu 8-gou" }],
    title: "Kaiju No. 8",
    title_english: "Kaiju No. 8 (Sub Indo)",
    title_japanese: "怪獣8号",
    type: "TV",
    source: "Manga",
    episodes: 12,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2024-04-13T00:00:00+00:00",
      to: "2024-06-29T00:00:00+00:00",
      prop: { from: { day: 13, month: 4, year: 2024 }, to: { day: 29, month: 6, year: 2024 } },
      string: "Apr 13, 2024 to Jun 29, 2024",
    },
    duration: "24 min per ep",
    rating: "PG-13 - Teens 13 or older",
    score: 8.35,
    scored_by: 260000,
    rank: 210,
    popularity: 90,
    members: 450000,
    favorites: 12000,
    synopsis:
      "Kafka Hibino bercita-cita bergabung dengan Pasukan Pertahanan untuk membasmi monster Kaiju. Saat bekerja sebagai pembersih bangkai monster, makhluk kecil tak dikenal memasuki tubuhnya dan memberinya kekuatan untuk bertransformasi menjadi Kaiju No. 8.",
    background: "Produksi gabungan Production I.G dan Studio Khara.",
    season: "spring",
    year: 2024,
    genres: [
      { mal_id: 1, name: "Action" },
      { mal_id: 24, name: "Sci-Fi" },
    ],
    themes: [],
    demographics: [{ mal_id: 27, name: "Shounen" }],
    studios: [{ mal_id: 10, name: "Production I.G" }],
    producers: [{ mal_id: 16, name: "TOHO animation" }],
  },
  {
    mal_id: 44511,
    url: "https://myanimelist.net/anime/44511/Chainsaw_Man",
    images: {
      jpg: {
        image_url: "https://cdn.myanimelist.net/images/anime/1806/126216.jpg",
        small_image_url: "https://cdn.myanimelist.net/images/anime/1806/126216t.jpg",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1806/126216l.jpg",
      },
      webp: {
        image_url: "https://cdn.myanimelist.net/images/anime/1806/126216.webp",
        small_image_url: "https://cdn.myanimelist.net/images/anime/1806/126216t.webp",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1806/126216l.webp",
      },
    },
    trailer: {
      youtube_id: "q15CRdE5Bv0",
      url: "https://www.youtube.com/watch?v=q15CRdE5Bv0",
      embed_url: "https://www.youtube.com/embed/q15CRdE5Bv0?enablejsapi=1&wmode=opaque&autoplay=1",
    },
    approved: true,
    titles: [{ type: "Default", title: "Chainsaw Man" }],
    title: "Chainsaw Man",
    title_english: "Chainsaw Man (Sub Indo)",
    title_japanese: "チェンソーマン",
    type: "TV",
    source: "Manga",
    episodes: 12,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2022-10-12T00:00:00+00:00",
      to: "2022-12-28T00:00:00+00:00",
      prop: { from: { day: 12, month: 10, year: 2022 }, to: { day: 28, month: 12, year: 2022 } },
      string: "Oct 12, 2022 to Dec 28, 2022",
    },
    duration: "24 min per ep",
    rating: "R - 17+ (violence & profanity)",
    score: 8.48,
    scored_by: 780000,
    rank: 135,
    popularity: 14,
    members: 1250000,
    favorites: 44000,
    synopsis:
      "Denji adalah seorang pemuda miskin yang bekerja sebagai Pemburu Iblis bersama anjing iblis gergaji mesinnya, Pochita, untuk melunasi utang ayahnya kepada Yakuza. Setelah dikhianati dan dibunuh, Pochita menyatu dengan jantung Denji dan menjadikannya Chainsaw Man.",
    background: "Karya Tatsuki Fujimoto yang dianimasikan oleh MAPPA.",
    season: "fall",
    year: 2022,
    genres: [
      { mal_id: 1, name: "Action" },
      { mal_id: 37, name: "Supernatural" },
    ],
    themes: [],
    demographics: [{ mal_id: 27, name: "Shounen" }],
    studios: [{ mal_id: 569, name: "MAPPA" }],
    producers: [{ mal_id: 16, name: "TOHO animation" }],
  },
];

export const FALLBACK_GENRES: GenreData[] = [
  { mal_id: 1, name: "Action", count: 4500 },
  { mal_id: 2, name: "Adventure", count: 3200 },
  { mal_id: 4, name: "Comedy", count: 6800 },
  { mal_id: 8, name: "Drama", count: 2900 },
  { mal_id: 10, name: "Fantasy", count: 5100 },
  { mal_id: 22, name: "Romance", count: 2400 },
  { mal_id: 24, name: "Sci-Fi", count: 3100 },
  { mal_id: 36, name: "Slice of Life", count: 1900 },
  { mal_id: 37, name: "Supernatural", count: 2100 },
  { mal_id: 41, name: "Suspense", count: 850 },
];
